# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\skku_gui_small.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1603, 921)
        self.textBrowser_log = QtGui.QTextBrowser(Dialog)
        self.textBrowser_log.setGeometry(QtCore.QRect(30, 390, 751, 461))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_log.setFont(font)
        self.textBrowser_log.setObjectName(_fromUtf8("textBrowser_log"))
        self.lcd_blue = QtGui.QLCDNumber(Dialog)
        self.lcd_blue.setGeometry(QtCore.QRect(150, 10, 561, 311))
        self.lcd_blue.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color: rgb(0, 0, 170);    \n"
"    background-color: rgb(255, 255, 255);\n"
"}"))
        self.lcd_blue.setNumDigits(3)
        self.lcd_blue.setProperty("intValue", 210)
        self.lcd_blue.setObjectName(_fromUtf8("lcd_blue"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 121, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1140, 10, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(1140, 180, 211, 181))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(1280, 380, 201, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lcd_green = QtGui.QLCDNumber(Dialog)
        self.lcd_green.setGeometry(QtCore.QRect(860, 10, 261, 161))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_green.sizePolicy().hasHeightForWidth())
        self.lcd_green.setSizePolicy(sizePolicy)
        self.lcd_green.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color: rgb(0, 210, 0);    \n"
"    background-color: rgb(255, 255, 255\n"
");\n"
"}"))
        self.lcd_green.setNumDigits(3)
        self.lcd_green.setProperty("intValue", 50)
        self.lcd_green.setObjectName(_fromUtf8("lcd_green"))
        self.lcd_red = QtGui.QLCDNumber(Dialog)
        self.lcd_red.setGeometry(QtCore.QRect(860, 190, 261, 151))
        self.lcd_red.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color: rgb(220, 0, 0);    \n"
"    background-color: rgb(255, 255, 255\n"
");\n"
"}"))
        self.lcd_red.setNumDigits(3)
        self.lcd_red.setObjectName(_fromUtf8("lcd_red"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(720, 70, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(710, 210, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(800, 390, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(810, 630, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(810, 750, 231, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pushButton_4 = QtGui.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(1280, 500, 201, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(1320, 620, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(1320, 740, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(1490, 380, 81, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(1490, 500, 81, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(1490, 620, 81, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(1490, 740, 81, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.lcd_black_1 = QtGui.QLCDNumber(Dialog)
        self.lcd_black_1.setGeometry(QtCore.QRect(1050, 390, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcd_black_1.setFont(font)
        self.lcd_black_1.setNumDigits(3)
        self.lcd_black_1.setObjectName(_fromUtf8("lcd_black_1"))
        self.lcd_black_2 = QtGui.QLCDNumber(Dialog)
        self.lcd_black_2.setGeometry(QtCore.QRect(1050, 510, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcd_black_2.setFont(font)
        self.lcd_black_2.setNumDigits(3)
        self.lcd_black_2.setObjectName(_fromUtf8("lcd_black_2"))
        self.lcd_black_3 = QtGui.QLCDNumber(Dialog)
        self.lcd_black_3.setGeometry(QtCore.QRect(1050, 620, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcd_black_3.setFont(font)
        self.lcd_black_3.setNumDigits(3)
        self.lcd_black_3.setObjectName(_fromUtf8("lcd_black_3"))
        self.lcd_black_4 = QtGui.QLCDNumber(Dialog)
        self.lcd_black_4.setGeometry(QtCore.QRect(1050, 750, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcd_black_4.setFont(font)
        self.lcd_black_4.setNumDigits(3)
        self.lcd_black_4.setObjectName(_fromUtf8("lcd_black_4"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(1210, 420, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(1210, 540, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(1210, 650, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(1210, 780, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(50, 330, 161, 51))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(230, 330, 141, 51))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(410, 330, 151, 51))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(590, 330, 151, 51))
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.pushButton_11 = QtGui.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(1140, 80, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(1370, 180, 211, 181))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(810, 510, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_14.setObjectName(_fromUtf8("label_14"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_reset)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_pause)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_1st)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_1st_cancel)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_2nd)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_2nd_cancel)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_3rd)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_3rd_cancel)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_4th)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_4th_cancel)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_force_start)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.bt_txt_save)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.textBrowser_log.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[ Scoring machine ] ver.1.3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">last update : 2018.06.04</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">author : RISE Lab (Hong-ryul Jung)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e-mail : jung.hr.1206@gmail.com</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">-----------------------------------------------</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Ready!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "Total\n"
"Time", None))
        self.pushButton.setText(_translate("Dialog", "Reset", None))
        self.pushButton_2.setText(_translate("Dialog", "Pause", None))
        self.pushButton_3.setText(_translate("Dialog", "Score -5\n"
"HP -5", None))
        self.label_3.setText(_translate("Dialog", "HP", None))
        self.label_4.setText(_translate("Dialog", "Minus\n"
"Score", None))
        self.label_5.setText(_translate("Dialog", "Collision\n"
"(except fallen)", None))
        self.label_7.setText(_translate("Dialog", "Hand\n"
"Touch", None))
        self.label_8.setText(_translate("Dialog", "Robot\n"
"Fallen #", None))
        self.pushButton_4.setText(_translate("Dialog", "Score -10\n"
"HP -5", None))
        self.pushButton_5.setText(_translate("Dialog", "HP -15", None))
        self.pushButton_6.setText(_translate("Dialog", "HP -5", None))
        self.pushButton_7.setText(_translate("Dialog", "Undo", None))
        self.pushButton_8.setText(_translate("Dialog", "Undo", None))
        self.pushButton_9.setText(_translate("Dialog", "Undo", None))
        self.pushButton_10.setText(_translate("Dialog", "Undo", None))
        self.label_10.setText(_translate("Dialog", "ea", None))
        self.label_11.setText(_translate("Dialog", "ea", None))
        self.label_12.setText(_translate("Dialog", "times", None))
        self.label_13.setText(_translate("Dialog", "times", None))
        self.checkBox.setText(_translate("Dialog", "Mission 1\n"
"Skipped", None))
        self.checkBox_2.setText(_translate("Dialog", "Mission 2\n"
"Skipped", None))
        self.checkBox_3.setText(_translate("Dialog", "Mission 3\n"
"Skipped", None))
        self.checkBox_4.setText(_translate("Dialog", "Mission 4\n"
"Skipped", None))
        self.pushButton_11.setText(_translate("Dialog", "Forced Start", None))
        self.pushButton_12.setText(_translate("Dialog", ".txt\n"
"Save", None))
        self.label_14.setText(_translate("Dialog", "Fallen\n"
"Obstacles", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

